spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: discovery-server
          uri: lb://discovery-server
          predicates:
            - Path=/discovery-server/**, /eureka/**
          filters:
           - RewritePath=/discovery-server/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8100/auth/realms/spring-boot-poc-realm/protocol/openid-connect/certs
  sleuth:
    reactor:
      # This is used to gain performance
      decorate-on-each: false
server:
  port: 9999
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
